#!/bin/sh
# to be called by git diff
# 
# place this in your .gitconfig to enable:
#
# [diff]
#   external = /path/to/git_diff_wrapper
# [pager]
#   diff =
#
# see: http://goo.gl/XY2yT

vimdiff "$2" "$5"

